// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package openapi

// Defines values for MType.
const (
	MTypeCounter MType = "counter"
	MTypeGauge   MType = "gauge"
)

// Defines values for UpdateOrCreateMetricByParamParamsType.
const (
	UpdateOrCreateMetricByParamParamsTypeCounter UpdateOrCreateMetricByParamParamsType = "counter"
	UpdateOrCreateMetricByParamParamsTypeGauge   UpdateOrCreateMetricByParamParamsType = "gauge"
)

// Defines values for GetValueByParamParamsType.
const (
	Counter GetValueByParamParamsType = "counter"
	Gauge   GetValueByParamParamsType = "gauge"
)

// BadRequestError defines model for bad_request_error.
type BadRequestError struct {
	// Message Описание ошибки
	Message string `json:"message"`

	// Status HTTP-код ошибки
	Status int `json:"status"`
}

// GenericError defines model for generic_error.
type GenericError struct {
	// Message Описание ошибки
	Message string `json:"message"`

	// Status HTTP-код ошибки
	Status int `json:"status"`
}

// InternalServerError defines model for internal_server_error.
type InternalServerError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// Metric defines model for metric.
type Metric struct {
	// Delta Значение для counter метрик (накопительное)
	Delta *int `json:"delta,omitempty"`

	// Hash Хеш для проверки целостности данных
	Hash *string `json:"hash,omitempty"`

	// Id Идентификатор метрики
	Id string `json:"id"`

	// Type Тип метрики
	Type string `json:"type"`

	// Value Значение метрики для gauge метрик
	Value *string `json:"value,omitempty"`
}

// MetricByBodyRequest defines model for metric_by_body_request.
type MetricByBodyRequest struct {
	// Id Идентификатор метрики
	Id string `json:"id"`

	// Type Тип метрики
	Type string `json:"type"`
}

// MetricRequest defines model for metric_request.
type MetricRequest struct {
	// Delta Значение для counter метрик (накопительное)
	Delta *int `json:"delta,omitempty"`

	// Id Идентификатор метрики
	Id string `json:"id"`

	// Type Тип метрики
	Type string `json:"type"`

	// Value Значение метрики для gauge метрик
	Value *string `json:"value,omitempty"`
}

// NotFoundError defines model for not_found_error.
type NotFoundError struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// ID defines model for id.
type ID = string

// MType defines model for type.
type MType string

// Value defines model for value.
type Value = string

// UpdateOrCreateMetricByParamParamsType defines parameters for UpdateOrCreateMetricByParam.
type UpdateOrCreateMetricByParamParamsType string

// UpdateOrCreateMetricsBatchJSONBody defines parameters for UpdateOrCreateMetricsBatch.
type UpdateOrCreateMetricsBatchJSONBody = []MetricRequest

// GetValueByParamParamsType defines parameters for GetValueByParam.
type GetValueByParamParamsType string

// UpdateOrCreateMetricByBodyJSONRequestBody defines body for UpdateOrCreateMetricByBody for application/json ContentType.
type UpdateOrCreateMetricByBodyJSONRequestBody = MetricRequest

// UpdateOrCreateMetricsBatchJSONRequestBody defines body for UpdateOrCreateMetricsBatch for application/json ContentType.
type UpdateOrCreateMetricsBatchJSONRequestBody = UpdateOrCreateMetricsBatchJSONBody

// GetValueByBodyJSONRequestBody defines body for GetValueByBody for application/json ContentType.
type GetValueByBodyJSONRequestBody = MetricByBodyRequest
