services:
  postgres:
    image: postgres:15-alpine
    container_name: metrics_dev_db
    env_file:
      - .env.dev
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
