env: "development"
storage:
  type: "mem"
logger:
  level: "debug"
  encoding: "console"
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
  initialFields: {}
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    levelEncoder: "lowercase"