env: "development"
storage:
  type: "mem"
  connection_string: "host=localhost port=5433 user=metrics_user password=metrics_password dbname=metrics_dev sslmode=disable"
template_path: "api/templates/metrics.html"
