// Code generated by cmd/reset. DO NOT EDIT.

package domain

// Reset сбрасывает Metrics к начальным значениям
func (r *Metrics) Reset() {
	if r == nil {
		return
	}
	r.ID = ""
	r.MType = ""
	if r.Delta != nil {
		*r.Delta = 0
	}
	if r.Value != nil {
		*r.Value = 0.0
	}
	r.Hash = ""
}
